### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by hhb19900618** [zzyspace/ZYShareView#1]
我好奇的是  下面的文字显示你为什么要使用 UITextView？

**Comment by zzyspace** [comment]
仔细观察一下原版微信的文字, 如果文字超过一行的话(比如"在Safari中打开"), 换行了之后, 第一行还是和其他item的文字对齐的. 如果用UILabel的话, 暂时没有发现适合的对齐模式可以这么设置.

**Comment by hhb19900618** [comment]
你的意思是希望下排文字居中显示

**Comment by zzyspace** [comment]
不是居中, 你可以先去看一下原版微信的分享, 文字一行和文字两行是怎么对齐的, 就懂了

**Comment by hhb19900618** [comment]
看到了呢   就是第一排还是保持左对齐，第二排保持居中啊

**Comment by zzyspace** [comment]
两排都是居中的. 但这个不是重点. 重点是要让每一个item的第一行文字都在同一条线上, 这个用UILabel的对齐模式暂时没找到方法可以实现

**Comment by hhb19900618** [comment]
哦  你是说y坐标对齐？

**Comment by zzyspace** [comment]
恩, 因为没有使用Autolayout, 所以就用UITextView的特性偷了个小懒 :)
